title: Deployment
ui:ObjectFieldTemplate: GSStepLayout
ui:options:
  formWidth: 1200
required:
  - installation
  - cluster
properties:
  installation:
    title: Installation
    type: object
    ui:field: GSInstallationPicker
    ui:options:
      autoSelectFirstValue: false
      widget: select
  cluster:
    title: Cluster
    type: object
    description: Workload cluster name
    ui:field: GSClusterPicker
    ui:options:
      installationNameField: installation.installationName
