title: Deployment
ui:ObjectFieldTemplate: GSStepLayout
ui:options:
  formWidth: 1200
required:
  - installation
  - cluster
properties:
  installation:
    title: Installation
    type: object
    required:
      - installationName
    properties:
      installationName:
        type: string
        description: Management cluster name
    ui:field: GSInstallationPicker
    ui:options:
      autoSelectFirstValue: false
      widget: select
  cluster:
    title: Cluster
    type: object
    required:
      - clusterName
      - clusterNamespace
    properties:
      clusterName:
        type: string
        description: Workload cluster name
      clusterNamespace:
        type: string
        description: Workload cluster namespace
    description: Workload cluster
    ui:field: GSClusterPicker
    ui:options:
      installationNameField: installation.installationName
