apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-deployment
  namespace: giantswarm
  title: App Deployment
  description: Deploy an app to a cluster.
spec:
  owner: group:team-honeybadger
  type: resource
  parameters:
    - title: Application
      ui:ObjectFieldTemplate: GSStepLayout
      ui:options:
        formWidth: 1200
      required:
        - entityRef
        - chartRef
        - chartTag
      properties:
        entityRef:
          title: Application
          description: Select the application you want to deploy.
          type: string
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              - kind: Component
                'metadata.tags': helmchart-deployable
        chartRef:
          title: Chart
          description: Some applications provide more than one Helm chart. In that case, please select the chart to deploy.
          type: string
          ui:field: GSChartPicker
          ui:options:
            entityRefField: entityRef
        chartTag:
          title: Version
          description: Select the version you want to deploy initially. Note that the options for automatic upgrades can overrule this.
          type: string
          ui:field: GSChartTagPicker
          ui:options:
            entityRefField: entityRef
            chartRefField: chartRef
        automaticUpgrades:
          title: Automatic upgrades
          type: string
          enum:
            - no-upgrades
            - patch-upgrades
            - minor-upgrades
            - major-upgrades
          default: no-upgrades
          ui:enumNames:
            - No automatic upgrades
            - Automatic patch upgrades
            - Automatic minor and patch upgrades
            - Automatic major, minor and patch upgrades
          ui:widget: radio
    - title: Cluster
      ui:ObjectFieldTemplate: GSStepLayout
      ui:options:
        formWidth: 1200
      required:
        - installation
        - cluster
      properties:
        installation:
          title: Installation
          description: First select an installation to pick a cluster from.
          type: object
          required:
            - installationName
          properties:
            installationName:
              type: string
              description: Management cluster name
          ui:field: GSInstallationPicker
          ui:options:
            autoSelectFirstValue: false
            widget: select
        cluster:
          title: Cluster
          description: Select any management or workload cluster to deploy the app to.
          type: object
          required:
            - clusterName
            - clusterNamespace
          properties:
            clusterName:
              type: string
            clusterNamespace:
              type: string
          ui:field: GSClusterPicker
          ui:options:
            installationNameField: installation.installationName
    - title: Deployment details
      ui:ObjectFieldTemplate: GSStepLayout
      ui:options:
        formWidth: 1200
      required:
        - name
        - targetNamespace
      properties:
        name:
          title: Name
          description: Name of the HelmRelease and OCIRepository resource. Also becomes part of Secret and ConfigMap resource names.
          type: string
          pattern: ^[a-z][-a-z0-9]*[a-z0-9]$
          ui:autofocus: true
          ui:field: GSTemplateStringInput
          ui:options:
            initialValue: '${{clusterNamePrefix(cluster)}}${{chartName(chartRef)}}'
        targetNamespace:
          title: Namespace
          type: string
          description: Namespace to deploy to in the target cluster. If it doesn't exist, it will be created.
          pattern: ^[a-z][-a-z0-9]*[a-z0-9]$
          ui:field: GSTemplateStringInput
          ui:options:
            initialValue: '${{clusterNamePrefix(cluster)}}${{chartName(chartRef)}}'
    - title: Configuration
      description: Here you can edit the application's configuration.
      ui:ObjectFieldTemplate: GSStepLayout
      ui:options:
        configurationDocs:
          chartRefField: chartRef
          chartTagField: chartTag
      properties:
        values:
          title: Values (stored as ConfigMap).
          type: string
          ui:field: GSYamlValuesEditor
          ui:options:
            chartRefField: chartRef
            chartTagField: chartTag
        secretValues:
          title: Secret values (stored as Secret).
          type: string
          ui:field: GSSecretYamlValuesEditor
          ui:options:
            secretsKey: SECRET_VALUES
            chartRefField: chartRef
            chartTagField: chartTag
        schemaValidation:
          type: boolean
          ui:field: GSYamlValuesValidation
          ui:options:
            chartRefField: chartRef
            chartTagField: chartTag
            valuesFields:
              - values
            secretValuesKeys:
              - SECRET_VALUES
    - title: Output options
      ui:ObjectFieldTemplate: GSStepLayout
      ui:options:
        formWidth: 1200
      required:
        - action
      properties:
        action:
          title: Desired result
          type: string
          enum:
            - apply
            - template
          default: apply
          ui:enumNames:
            - Deploy the application
            - Display the manifest (e.g. for use in a GitOps repository)
          ui:widget: radio
      dependencies:
        action:
          allOf:
            - if:
                properties:
                  action:
                    const: apply
                required:
                  - action
              then:
                properties:
                  userToken:
                    type: object
                    ui:field: GSOIDCToken
                    ui:options:
                      secretsKey: USER_OIDC_TOKEN
                      installationNameField: installation.installationName
  steps:
    - id: fetchTemplate
      name: Template manifests
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.cluster.clusterNamespace }}
          clusterName: ${{ parameters.cluster.clusterName }}
          isManagementCluster: ${{ parameters.cluster.isManagementCluster }}
          targetNamespace: ${{ parameters.targetNamespace }}
          chartRef: ${{ parameters.chartRef }}
          chartTag: ${{ parameters.chartTag }}
          automaticUpgrades: ${{ parameters.automaticUpgrades }}
          values: ${{ parameters.values }}
          secretValues: ${{ secrets.SECRET_VALUES }}
    - id: cleanup
      name: Clean up
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: manifest.yaml
            find: \n\s*\n
            replaceWith: "\n"
            matchRegex: true
    - id: parseFile
      name: Print manifests
      action: roadiehq:utils:fs:parse
      input:
        path: manifest.yaml
    - id: apply
      if: ${{ parameters.action == 'apply' }}
      action: kube:apply
      name: Apply to cluster
      input:
        namespaced: true
        clusterName: ${{ parameters.installation.installationName }}
        token: ${{ secrets.USER_OIDC_TOKEN }}
        manifest: ${{ steps.parseFile.output.content }}
  output:
    links:
      - title: Go to deployment
        url: /deployments/${{ parameters.installation.installationName }}/helmrelease/${{ parameters.cluster.clusterNamespace }}/${{ parameters.name }}
    text:
      - title: Manifests
        content: |
          ```yaml
          ${{ steps.parseFile.output.content }}
          ```
