name: Template tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-26.04
    defaults:
      run:
        working-directory: test
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1  # v7.1.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: test/package-lock.json
      - name: Install
        run: npm ci
      - name: Render the templates and check the manifests
        run: npm test
